version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: builder
    volumes:
      - ./services/app:/go/src/app
    tty: true
    ports:
      - "8000"
    command: sh -c "fresh;"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
