version: 2
jobs:
  build_docker_nginx:
    environment:
      AWS_ECR_HOST_JP: aaaa
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'docker build'
          command: |
      - run:
          name: 'docker push'
          command: |

workflows:
  version: 2
  build:
    jobs:
      - build_docker_nginx:
          filters:
            branches:
              only:
                - dev
