version: 2
jobs:
  build_docker_nginx:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'aws cli install'
          command: |
            if [[ ! -d aws-cli ]]; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install --install-dir ~/work/aws-cli
            fi
            export PATH=$PATH:$HOME/work/aws-cli/v2/current/bin
            aws --version
      - run:
          name: 'docker build'
          command: |
            set -x
            pushd docker/nginx
            docker version
            echo "## docker build start ##"
            docker build -t nginx:master .
      - run:
          name: 'docker push'
          command: |
            pushd docker/nginx
            echo "## docker push start ##"
            $ aws ecr get-login-password | docker login --username AWS --password-stdin ${AWS_ECR_HOST_URL}
            docker tag nginx:master ${AWS_ECR_HOST_URL}/nginx:master
            docker push ${AWS_ECR_HOST_URL}/nginx:master

workflows:
  version: 2
  build:
    jobs:
      - build_docker_nginx:
          filters:
            branches:
              only: dev
