version: 2
jobs:
  build_docker_nginx:
    docker:
      - image: cimg/go:1.16
    environment:
      AWS_ECR_HOST_URL: $AWS_ECR_HOST_URL
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'docker build'
          command: |
            set -x
            pushd docker/nginx
            docker version
            echo "## docker build start ##"
            docker build -t nginx:master .
      - run:
          name: 'docker push'
          command: |
            pushd docker/nginx
            echo "## docker push start ##"
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker tag nginx:master ${AWS_ECR_HOST_URL}/nginx:master
            docker push ${AWS_ECR_HOST_URL}/nginx:master

workflows:
  version: 2
  build:
    jobs:
      - build_docker_nginx:
          filters:
            branches:
              only: dev
