version: 2
jobs:
  build_docker_nginx:
    docker:
      - image: cimg/go:1.16
    environment:
      AWS_ECR_HOST_JP: aaaa
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'docker build'
          command: |
            echo "build start"
      - run:
          name: 'docker push'
          command: |
            echo "image push start"

workflows:
  version: 2
  build:
    jobs:
      - build_docker_nginx:
          filters:
            branches:
              only: dev
